<a id="Top"></a>
<p><span class="label label-default">Last Updated: 15th May 2015</span></p>
<p><strong>This Terms Of Service Agreement (TOS) is a formal and legally binding agreement between Afford A Host (we, Company) and the service user (you, Subscriber). Use of our service constitutes acceptance and agreement to the TOS in full.</strong></p>
<p>
<h3>Contents</h3>
</p>
<p><strong><a href="#1">1) Purpose and Overview of the TOS</a><br />
  <a href="#2">2) Specific Violations of the TOS</a><br />
  <a href="#3">3) Security</a><br />
  <a href="#4">4) Network Performance</a><br />
  <a href="#5">5) Payment Policy</a><br />
  <a href="#6">6) General Operations</a><br />
  <a href="#7">7) Violation Reporting</a> <br />
  <a href="#8">8) Violation Procedures</a><br />
  <a href="#9">9) Miscellaneous Provisions</a><br />
  </strong></p>
<a id="1"></a>
<h3>1) Purpose and Overview of the TOS</h3>
<p>The TOS is provided to give our Subscribers a clear understanding of what we expect of them while using our services. All users of our services including those who access our services but do not have accounts, as well as those who pay a service fee to subscribe to the services, must comply with our TOS.</p>
<p>We support the uncensored flow of information and ideas over the Internet and do not actively monitor subscriber activity under normal circumstances. Similarly, we do not exercise editorial control over the content of any website, e-mail transmission, newsgroups, or other material created or accessible over or through the services, except for certain proprietary websites. However, in accordance with our TOS, we may remove any materials that, in our sole discretion, may be illegal, may subject us to liability, or which may violate the TOS. We may cooperate with legal authorities and/or third parties in the investigation of any suspected or alleged crime or civil wrongdoing. Your violation of the TOS may result in the suspension or immediate termination of your account without prior notice.</p>
<p>The following are guidelines for the establishment and enforcement of the TOS:</p>
<p>-Ensure reliable service to our customers<br />
  -Ensure security and privacy of our systems and network, as well as the networks and systems of others<br />
  -Comply with existing laws<br />
  -Maintain our reputation as a responsible service provider<br />
  -Encourage responsible use of the Internet and discourage activities which reduce the usability and value of Internet services<br />
  -Preserve the value of Internet resources as a conduit for free expression and exchange of information<br />
  -Preserve the privacy and security of individual users</p>
<p>While we are committed to the principles of free speech, certain activities that may be damaging to the resources of both us and the Internet and cannot be permitted under the guise of free speech. The resources of us and the Internet are limited, and abuse of these resources by one user has a negative impact on the entire community.</p>
<p>We do not routinely monitor the activity of accounts except for measurements of system utilization and the preparation of billing records. However, in our efforts to promote good citizenship within the Internet community, we will respond appropriately if we become aware of inappropriate use of our service.</p>
<p>If you violate the TOS, we reserve the right to terminate your service without notice. We prefer to advise Subscribers of inappropriate behavior and any necessary corrective action, however, flagrant violations of the TOS will result in immediate termination of service. Our failure to enforce this policy, for whatever reason, shall not be construed as a waiver of our right to do so at any time.</p>
<a href="#Top">^Top</a><br />
<a id="2"></a>
<p>
<h3>2) Specific Violations of the TOS</h3>
</p>
<p>By using our services you agree not to commit any of the following specific violation of the TOS. The following constitute specific violations of the TOS:</p>
<p><strong>Illegal use: </strong>Our services may not be used for illegal purposes, or in support of illegal activities. We reserve the right to cooperate with legal authorities and/or injured third parties in the investigation of any suspected crime or civil wrongdoing. If anything is not legal in the United Kingdom or United States of America, it is not permitted to reside on our servers. If illegal content or usage is found, the account will be suspended and/or terminated. Subscriber agrees that the Company may disclose any and all subscriber information including assigned IP numbers, account history, account use, etc. to any law enforcement agent who makes a written request without further consent or notification to the Subscriber.</p>
<p><strong>Harm to minors: </strong>Use of our service to harm, or attempt to harm, minors in any way, including, but not limited to child pornography is prohibited. Violation of this policy will result in immediate termination of your service and a report will be made to law enforcement authorities.</p>
<p><strong>Threats: </strong>Use of our service to transmit any material (by e-mail, uploading, posting or otherwise) that threatens or encourages bodily harm or destruction of property is prohibited.</p>
<p><strong>Harassment: </strong>Use of our service to transmit any material (by e-mail, uploading, posting or otherwise) that harasses another is prohibited.</p>
<p><strong>Fraudulent activity:</strong> Use of our service to make fraudulent offers to sell or buy products, items, or services, or to advance any type of financial scam such as &quot;pyramid schemes,&quot; &quot;ponzi schemes,&quot; and &quot;chain letters&quot; is prohibited This also includes any knowing misrepresentation or misleading statement, writing or activity made with the intent that the person receiving it will act upon it. </p>
<p><strong>Forgery or impersonation: </strong>Adding, removing or modifying identifying network header information in an effort to deceive or mislead is prohibited. Attempting to impersonate any person by using forged headers or other identifying information is prohibited. Forging any message header, in part or whole, of any electronic transmission, originating or passing through our service is in violation of the TOS. The use of anonymous remailers or nicknames does not constitute impersonation. </p>
<p><strong>Unsolicited commercial e-mail/Unsolicited bulk e-mail (SPAM): </strong>Use of our service to transmit any unsolicited commercial or unsolicited bulk e-mail is expressly prohibited. Violation of this SPAM policy will result in severe penalties. Upon notification of an alleged violation of our SPAM policy, we will initiate an investigation. During the investigation, we may restrict Subscriber access to the network to prevent further violations. If a Subscriber is found to be in violation of our SPAM policy, we may, at our sole discretion, restrict, suspend or terminate the Subscriber's account. Further, we reserve the right to pursue civil remedies for any costs associated with the investigation of a substantiated policy violation. We will notify law enforcement officials if the violation is believed to be a criminal offense. Anyone using our service to host websites or services that support spammers or cause any of our IP space to be listed in any of the various Spam Databases will have their account(s) immediately suspended. The account will not be unsuspended until such time that you agree to remove any and all traces of the offending material immediately upon reconnection. First violations of this policy will result in an &quot;Administrative Fee&quot; of &pound;25 and your account will be reviewed for possible immediate termination. Severe violations may result in immediate and permanent removal of the account(s) from our network without notice to the customer. A second violation will result in an &quot;Administrative Fee&quot; of &pound;50 and immediate termination of your account.</p>
<p><strong>E-mail/News Bombing: </strong>Malicious intent to impede another person's use of electronic mail services or news will result in the immediate termination of the offending account.</p>
<p><strong>Usenet Abuse/Spamming:</strong> We have a zero tolerance policy for the use of our service for the posting of messages or commercial advertisements which violate the rules, regulations, or charter of any newsgroups or mailing list. Commercial messages that are appropriate under the rules of a newsgroup or mailing list or that are solicited by the recipients are permitted.</p>
<p><strong>Unauthorised access: </strong>Use of our service to access, or to attempt to access, the accounts of others, or to penetrate, or attempt to penetrate, security measures of ours or another entity's computer software or hardware, electronic communications system, or telecommunications system, whether or not the intrusion results in the corruption or loss of data, is expressly prohibited and the offending account is subject to immediate termination. You may not attempt to circumvent user authentication or security of any host, network or account. This includes, but is not limited to, accessing data not intended for you, logging into or making use of a server or account you are not expressly authorised to access, or probing the security of other networks. Use or distribution of tools designed for compromising security is prohibited. Examples of these tools include, but are not limited to, password guessing programs, cracking tools or network probing tools. Violations of system or network security may result in civil or criminal liability. We will investigate occurrences, which may involve such violations and may involve, and cooperate with, law enforcement authorities in prosecuting users who are involved in such violations. </p>
<p><strong>Copyright or trademark infringement: </strong>Use of our service to transmit any material (by e-mail, uploading, posting or otherwise) that infringes any copyright, trademark, patent, trade secret or other proprietary rights of any third party, including, but not limited to, the unauthorised copying of copyrighted material, the digitization and distribution of photographs from magazines, books, or other copyrighted sources, and the unauthorised transmittal of copyrighted software is prohibited. This also includes intellectual property rights. Distribution and/or posting of copyrighted or the aforementioned infringements will not be tolerated. </p>
<p><strong>Collection of personal data: </strong>Use of the service to collect, or attempt to collect, personal information about third parties without their knowledge or consent is prohibited.</p>
<p><strong>Network disruptions and unfriendly activity: </strong>Use of the service for any activity which affects the ability of other people or systems to use our services or the Internet is prohibited. This includes &quot;denial of service&quot; (DOS) attacks against another network host or individual user. Interference with or disruption of other network users, services or equipment is prohibited. This includes, but is not limited to: &quot;flooding&quot; of networks, deliberate attempts to overload a service, and attempts to &quot;crash&quot; a host. It is the Subscriber's responsibility to ensure that their account(s) are configured in a secure manner. A Subscriber may not, through action or inaction, allow others to use their account for illegal or inappropriate actions. A Subscriber may not permit their account, through action or inaction, to be configured in such a way that gives a third party the capability to use their account in an illegal or inappropriate manner. Unauthorised entry and/or use of another company and/or individual's computer system will result in immediate account termination. We will not tolerate any Subscriber attempting to access the accounts of others, or penetrate security measures of other systems, whether or not the intrusion results in corruption or loss of data. We reserve the right, to drop the section of IP space involved in Spam or Denial-of-Service complaints if it is clear that the offending activity is causing great harm to parties on the Internet. In particular, if open relays are on your account, or if denial of service attacks are originating from your account. In certain rare cases, we may have to do this before attempting to contact you. If we do this, we will contact you as soon as is feasible.</p>
<p><strong>Distribution of Viruses:</strong> Intentional distributions of software or anything that attempts to and/or causes damage, harassment, or annoyance to persons, data, and/or computer systems are prohibited. Such an offense will result in the immediate termination of the offending account.</p>
<p><strong>Inappropriate Use of Software: </strong>Use of software or any device that would facilitate a continued connection, i.e. pinging, while using our services could result in suspension of service.</p>
<p><strong>IRC networks:</strong> It is forbidden to host IRC (Internet Relay Chat) that is part of or connected to another IRC network or server. Accounts found to be connecting to or part of these networks will be immediately suspended without notice. The account will not be unsuspended until such time that you agree to remove any and all traces of the offending material immediately upon reconnection. Severe violations may result in immediate and permanent removal of the account(s) from our network without notice to the customer. Any user who commits a second violation will be immediately and permanently removed from our network without notice.</p>
<p><strong>Streaming Video and Audio: </strong>Streaming Video and Audio is not permitted on our servers. You must zip the content to prevent this if you wish to have it hosted, and like everything else this content must be legal and in compliance with our copyright guidelines.</p>
<p><strong>Eggdrop Scripts:</strong> Eggdrop scripts/bots and IRC bots of any type are not allowed, these are grounds for immediate account deletion.</p>
<p><strong>Adult Material:</strong> Adult Material is not allowed, unless specified in your package deal. If a website is found to contain adult material that is not on an adult approved server/package, the website will be suspended.</p>
<p><strong>Objectionable Material:</strong> You may not use our service to publish material, which we determine, at our sole discretion, to be unlawful, indecent or objectionable. For purposes of this policy, &quot;material&quot; refers to all forms of communications including but not limited to: narrative descriptions, graphics (including photographs, illustrations, images, drawings, logos), executable programs, video recordings, and audio recordings. If you unsure if your content is objectionable, please contact us before posting it. </p>
<p><strong>Chinese Forums: </strong>Chinese Forums are not allowed on our network. These sites require too much CPU usage. They typically require a dedicated server to run properly. If they are found on any server we will suspend and/or terminate them.</p>
<p><strong>ANIME: </strong>Anime websites are not allowed on our network. If an Anime website is found we will terminate the account. These sites are not allowed on our servers because most of them are illegal, and almost inevitably cause server problems.</p>
<p><strong>Use of our service by minors: </strong>Persons under the age of eighteen (18) must have permission from their parent/guardian to use our services. By signing up for our service, you agree that you are over the age of eighteen, OR your parent/guardian has permitted you to do so and has read and agreed to the TOS, and has accepted responsibility for any actions you may take as a minor under their custody.</p>
<a href="#Top">^Top</a><br />
<a id="3"></a>
<p>
<h3>3) Security</h3>
</p>
<p>By using our services you agree to adopt adequate security measures to prevent or minimise unauthorised use of your account. Your password provides access to your account. It is your responsibility to keep your password secure. Sharing your password and account access with unauthorised users is prohibited. You should take care to prevent others from using your account since you will be held responsible for such use.</p>
<p>Subscribers will be held responsible for any activity by third parties using their accounts in a way that violates the TOS. You are responsible for any misuse of your account, even if the inappropriate activity was committed by a friend, family member, guest or employee. Therefore, you must take steps to ensure that others do not gain unauthorised access to your account.</p>
<a href="#Top">^Top </a><br />
<a id="4"></a>
<p>
<h3>4) Network Performance</h3>
</p>
<p>By using our service you agree to abide by this policy. Our services operate on shared resources. Excessive use or abuse of these shared network resources by one customer may have a negative impact on all other customers. Misuse of network resources in a manner which impairs network performance is prohibited by this policy and may result in termination of your account.</p>
<p>You are prohibited from excessive consumption of resources, including CPU time, memory, disk space and session time. You may not use resource-intensive programs which negatively impact other customers or the performances of our systems or networks. This may include certain scripts or forums that put excessive use on the SQL server in a way which degrades performance for other users. We reserve the right to terminate or limit such activities. Additionally, if your account(s) becomes the target of denial-of-service (DOS or DDOS) or other malicious attacks against the server, we reserve the right to end your service.</p>
<a href="#Top">^Top</a><br />
<a id="5"></a>
<p>
<h3>5) Payment Policy</h3>
</p>
<p>By using our services you agree to the following payment policy and instructions.</p>
<p>Refunds: We offer a five-day money-back guarantee. If during the first five days after subscribing you are unhappy with the service you may submit a refund request. Any such request must be made in writing and must be made before the end of five days from the moment your initial payment was made. In such case your payment will be refunded (less any set-up fees or special costs) and your account will be deleted from our network upon refunding. The five-day money-back guarantee only applies to the first payment made on a new account. After the initial seven-day period, no refunds will be made at any time for the first payment on a new account. All subsequent payments made to Splash! Web Hosting are absolutely non-refundable. If you dispute a charge to your credit card issuer or take any action that results in a payment being reversed that, in our sole discretion is a valid charge under the provisions of the TOS, you agree to pay us an &quot;Administrative Fee&quot; of &pound;50.</p>
<p>Payment/Subscription: Establishment of this service is dependent upon receipt by the Company of payment of stated charges. We require that all Subscribers use an automatically recurring payment subscription through one of our payment processors (currently Paypal). Your recurring subscription must remain active at all times for your account to remain activated. If a subscription becomes inactive and/or is cancelled, we will suspend the account and issue a warning to the Subscriber to their email address on file. If the subscription is not rectified within 7-days of the warning we will delete the account from the server. Such termination or denial will not relieve Subscriber of responsibility for the payment of all accrued charges, plus reasonable interest and any collection fees. We may allow some users to purchase our services with a one-time payment or subscription that is not automatically recurring. Any such allowance does not forfeit our right to require any such user to activate a recurring subscription at any time.</p>
<p>Cancellation: All cancellations must be made by the subscriber with a verbal or written request to cancel accounts. We will not wait until the end of any advertised or perceived billing cycle, and we will not refund any unused portions of any subscription payment. We require that a recurring subscription be active at all times and will therefore delete the account upon termination of the subscription.</p>
<p>Service Rates: Subscriber acknowledges that the nature of the service furnished and the initial rates and charges have been communicated to Subscriber. Subscriber is aware that the Company may prospectively change the specified rates and charges from time to time. The promotional offer is contingent upon Company achieving and maintaining its cost of service goals including but not limited to rates charged to company by its suppliers.</p>
<a href="#Top">^Top</a><br />
<a id="6"></a>
<p>
<h3>6) General Operations</h3>
</p>
<p>By using our service you agree to the following policy and limitations pertaining to our services.</p>
<p>Uptime: Subscriber acknowledges that the service provided is of such a nature that service can be interrupted for many reasons other than the negligence of the Company and that damages resulting from any interruption of service are difficult to ascertain. Therefore, Subscriber agrees that the Company shall not be liable for any damages arising from such causes. In no event shall the Company be liable for any special or consequential damages, loss or injury. Although many of our own network providers guarantee an uptime of 99% or more, we make no guarantees about uptime performance because we realise there are influencing factors that are outside of our control, and in most cases even outside the control of the data centers and network providers we work with.</p>
<p>Support Boundaries: We provide technical support to our Subscribers. We limit our technical support to our areas of expertise. We provide support related to your account or virtual site's physical functionality. We do not offer technical support for application specific issues such as cgi programming, html, or any other such issue. We provide a variety of support information and options to our Subscribers. These support options can be found on the support page of our website.</p>
<p>Abuse of Our Staff or Network Staff: Abuse towards our staff or our network staff will not be tolerated. If you use foul language, threaten us, or do anything we find offensive, we may suspend and/or delete your account. Per our payment policy we offer no refunds.</p>
<p>Internet Protocol (IP) Address Ownership: If we assign a Subscriber an IP address for the Subscriber's use, the right to use that IP address shall belong only to us, and Subscriber shall have no right to use that IP address except as permitted by us in our sole discretion in connection with the services. We shall maintain and control ownership of all IP numbers and addresses that may be assigned to Subscriber by us, and we reserve the right to change or remove any and all such IP numbers and addresses, in our sole and absolute discretion. Our allocation of IP addresses is limited by the policies set forth by ARIN (American Registry for Internet Numbers). These policies state that use of IP addresses for IP-based virtual hosts will not be accepted as justification for new IP addresses. What this means to you is that you MUST use name-based hosting where possible. We will periodically review IP address usage, and if we find that clients are using IP addresses where name-based hosting could be used, we will revoke authorization to use those IP addresses that could be used with name-based hosting.</p>
<p>Bandwidth and Disk Usage: Subscriber agrees that bandwidth and disk usage shall not exceed the quota for the services ordered by Subscriber on the order form (the &quot;Agreed Usage&quot;). We will monitor Subscriber's bandwidth and disk usage. We have the right to take corrective action if Subscriber's bandwidth or disk usage exceeds the Agreed Usage in our sole discretion. Such corrective action may include the assessment of additional charges, or disconnection or discontinuance of the service. If we take any corrective action under this section, Subscriber shall not be entitled to a refund of any fees paid in advance prior to such action.</p>
<a href="#Top">^Top </a><br />
<a id="7"></a>
<p>
<h3>7) Violation Reporting</h3>
</p>
<p>By using our service you agree to report violations of the TOS to us. Anyone who believes that there is a violation of our TOS should direct such information to us by email immediately. If available, please provide the following information:</p>
<p>-The IP address used to commit the alleged violation<br />
  -The date and time of the alleged violation, including the time zone or offset from GMT<br />
  -Evidence of the alleged violation</p>
<p>E-mail with full header information provides all of the above, as do system log files. Other situations will require different methods of providing the above information. We may take any one or more of the following actions in response to complaints:</p>
<p>-Issue written or verbal warnings<br />
  -Suspend the Subscriber's newsgroup posting privileges<br />
  -Suspend the Subscriber's account<br />
  -Terminate the Subscriber's account<br />
  -Bill the Subscriber for administrative costs and/or reactivation charges<br />
  -Bring legal action to enjoin violations and/or to collect damages, if any, caused by violations</p>
<a href="#Top">^Top</a><br />
<a id="8"></a>
<p>
<h3>8) Violation Procedures</h3>
</p>
<p>By using our services you understand and agree with the following procedures and policies. </p>
<p>We are under no duty to look at each Subscriber's or user's activities to determine if a violation of the TOS has occurred, nor do we assume any responsibility through our TOS to monitor or police Internet-related activities. </p>
<p><strong>First violation:</strong> Any Subscriber, which we determine to have violated any element of the TOS, shall receive an email, warning them of the violation. The service may be subject at our discretion to a temporary suspension pending a Subscriber's agreement in writing, to refrain from any further violations. </p>
<p><strong>Second Violation:</strong> Subscribers that we determine to have committed a second violation of any element of this Acceptable Use Policy shall be subject to immediate suspension or termination of service without further notice. </p>
<p><strong>Suspension of Service or Cancellation:</strong> We reserve the right to suspend network access to any Subscriber if in the judgment of the network administrators the customer's account is the source or target of the violation of the TOS or for any other reason which we choose. If inappropriate activity is detected, all accounts of the Subscriber in question will be deactivated until an investigation is completed. Prior notification to the Subscriber is not assured. In extreme cases, law enforcement will be contacted regarding the activity.</p>
<a href="#Top">^Top</a><br />
<a id="9"></a>
<p>
<h3>9) Miscellaneous Provisions</h3>
</p>
<p><strong>Indemnification:</strong> In agreeing to the TOS, Subscriber indemnifies us for any violation of the TOS that results in loss to us or the bringing of any claim against us by any third-party. This means that if we are sued because of a Subscriber's or a customer of a Subscriber's activity, the Subscriber will pay any damages awarded against us, plus all costs and attorney's fees.</p>
<p><strong>Contact Information:</strong> You must provide us with, and keep current, good contact information for yourself including an E-mail address and telephone number. If we fail to communicate any information to you due to a non-current, inoperative, or incorrect email address you are still responsible and accountable for any such information we attempted to communicate.</p>
<p><strong>Waiver:</strong> A waiver by the Company of any breach of any provision of the TOS by Subscriber shall not operate as or be construed as a continuing or subsequent waiver thereof or as a waiver of any breach of any other provision thereof.</p>
<p><strong>Assignment:</strong> Subscriber shall not transfer or assign the TOS without the prior written consent of the Company. Company may assign the TOS at anytime without consent from or notice to Subscriber. Company reserves the right to cancel Subscriber's rights under this contract at any time without further obligation.</p>
<p><strong>3rd Party Disclaimer:</strong> We take no responsibility for any material input by others and not posted to our website by us. We are not responsible for the content of any other websites linked to us; links are provided as Internet navigation tools only. We disclaim any responsibility for any such inappropriate use and any liability to any person or party for any other person or party's violation of this policy.</p>
<p><strong>Disclaimer of warranties:</strong> We are not responsible for any damages your business may suffer. We do not make implied or written warranties for any of our services. We deny any warranty or merchantability for a specific purpose. This includes loss of data resulting from delays, non-deliveries, wrong delivery, and any and all service interruptions caused by us.</p>
<p><strong>3rd Party Software and Services:</strong> We may provide you access to third party software and/or services (&quot;Third Party Products &quot;) through reseller relationships we have established with certain commercial vendors. Subscriber understands that product support for Third Party Products is provided by us and not by the Third Party Vendor, unless otherwise notified. Neither us nor any Third Party Vendor makes any representations or warranties, express or implied, regarding any Third Party Products. Subscriber expressly acknowledges and agrees that use of third party products is at customer's sole risk and such third party products are provided &quot;as is&quot; and without representation or warranty of any kind from us or any third party vendor, including without limitation, any implied warranty of merchantability, fitness for a particular purpose, accuracy or completeness of responses or results, correspondence to description, or non-infringement of third party rights. To the maximum extent permitted by applicable law, neither us nor any third party vendor will be legally responsible for any damages, whether direct, indirect, or consequential, arising from the use or inability to use any third party product. Subscriber agrees to observe the terms of any license and/or applicable end-user subscriber agreement for third party products and that customer shall be fully liable to third party vendors and us with respect to any improper use of such third party products or violation of license agreements with them and/or applicable end user subscriber agreements. Subscriber agrees not to remove, modify or obscure any copyright, trademark or other proprietary rights notices that appear on Third Party Products or that appear during the use of Third Party Products. Subscriber further agrees not to reverse engineer, decompile, or disassemble the Third Party Products.</p>
<p><strong>Revisions to the TOS:</strong> We reserve the right to revise, amend, or modify the TOS at any time and in any manner. In such case the amended or revised TOS will be posted to our website. Subscriber understands that changes to the TOS shall not be grounds for early contract termination or non-payment.</p>
<p><strong>Location and Severability:</strong> The TOS shall be construed in all respects in accordance with the laws of UK and US. If any part of the TOS is found to be invalid or unenforceable by law, the remainder of the TOS will remain enforceable and in full effect.</p>
<a href="#Top">^Top</a><br />
